name: Create DevBox Project

on:
 workflow_dispatch:
   inputs: 
     projectTeamName:
       description: 'The name of the devbox project'
       required: true
       type: string

jobs:
  
  create-devbox-project:

    runs-on: ubuntu-latest

    steps:
      - name: Create DevBox Project        
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.SHARED_RESOURCE_GROUP_NAME }}}
          template: iac/main.bicep
          parameters: location=${{ env.LOCATION }} managementRgName=${{ env.RG_NAME }} 
      
    